-- Formal schema extension for STM32N647 agriculture dashboard.
-- Safe to run in Supabase SQL Editor: it never deletes or truncates data.
-- Device JSON v1.0 body is unchanged; security metadata stays in headers/secrets.

begin;

alter table public.diagnosis_records
  add column if not exists model_version text,
  add column if not exists latency_ms integer,
  add column if not exists raw_payload jsonb,
  add column if not exists system_status text not null default 'UNKNOWN',
  add column if not exists sensor_status text not null default 'UNKNOWN';

alter table public.diagnosis_records
  drop constraint if exists diagnosis_records_risk_level_check,
  add constraint diagnosis_records_risk_level_check
    check (risk_level in ('LOW', 'MEDIUM', 'MEDIUM_HIGH', 'HIGH', 'CRITICAL', 'UNKNOWN'));

alter table public.diagnosis_records
  drop constraint if exists diagnosis_records_pump_action_check,
  add constraint diagnosis_records_pump_action_check
    check (pump_action in ('ON', 'OFF', 'NONE', 'REQUEST'));

alter table public.diagnosis_records
  drop constraint if exists diagnosis_records_fan_action_check,
  add constraint diagnosis_records_fan_action_check
    check (fan_action in ('ON', 'OFF', 'NONE', 'REQUEST'));

create table if not exists public.device_registry (
  id bigint generated by default as identity primary key,
  device_id text not null unique check (device_id in ('Node01', 'Node02', 'Node03')),
  display_name text not null,
  region_name text not null,
  crop_type text not null,
  is_active boolean not null default true,
  token_version text not null default 'v1',
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.device_telemetry (
  id bigint generated by default as identity primary key,
  record_id bigint references public.diagnosis_records(id) on delete set null,
  device_id text not null,
  temperature_c double precision,
  humidity_percent double precision,
  light_lux double precision,
  soil_moisture_percent double precision,
  liquid_level text check (liquid_level in ('OK', 'LOW', 'UNKNOWN')),
  current_ma numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.actuation_logs (
  id bigint generated by default as identity primary key,
  record_id bigint references public.diagnosis_records(id) on delete set null,
  device_id text not null,
  pump_action text not null check (pump_action in ('ON', 'OFF', 'NONE', 'REQUEST')),
  fan_action text not null check (fan_action in ('ON', 'OFF', 'NONE', 'REQUEST')),
  pump_duration_s integer not null default 0 check (pump_duration_s >= 0),
  fan_duration_s integer not null default 0 check (fan_duration_s >= 0),
  alarm text not null default 'NONE',
  safety_blocked boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  device_id text,
  event_type text not null,
  severity text not null check (severity in ('INFO', 'WARN', 'HIGH', 'CRITICAL')),
  reason text not null,
  remote_addr text,
  created_at timestamptz not null default now()
);

create table if not exists public.model_versions (
  id bigint generated by default as identity primary key,
  model_name text not null,
  model_type text not null check (model_type in ('pc_yolo', 'onnx', 'stm32_npu', 'device_report')),
  class_count integer not null check (class_count > 0),
  class_mapping_json jsonb not null,
  accuracy numeric,
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

insert into public.device_registry (device_id, display_name, region_name, crop_type)
values
  ('Node01', 'Node01 番茄区', '番茄区', '番茄'),
  ('Node02', 'Node02 甜椒区', '甜椒区', '甜椒'),
  ('Node03', 'Node03 马铃薯区', '马铃薯区', '马铃薯')
on conflict (device_id) do update
set display_name = excluded.display_name,
    region_name = excluded.region_name,
    crop_type = excluded.crop_type,
    updated_at = now();

insert into public.model_versions (
  model_name,
  model_type,
  class_count,
  class_mapping_json,
  accuracy,
  is_active
)
values (
  'stm32n647_device_report_v1',
  'device_report',
  8,
  '{
    "0": "Pepper_Bell_Bacterial_Spot",
    "1": "Pepper_Bell_Healthy",
    "2": "Potato_Early_Blight",
    "3": "Potato_Late_Blight",
    "4": "Potato_Healthy",
    "5": "Tomato_Early_Blight",
    "6": "Tomato_Late_Blight",
    "7": "Tomato_Healthy"
  }'::jsonb,
  null,
  true
)
on conflict do nothing;

create index if not exists idx_diagnosis_records_device_created_at
  on public.diagnosis_records (device_id, created_at desc);

create index if not exists idx_diagnosis_records_risk_created_at
  on public.diagnosis_records (risk_level, created_at desc);

create index if not exists idx_diagnosis_records_class_created_at
  on public.diagnosis_records (disease_class_id, created_at desc);

create index if not exists idx_device_telemetry_device_created_at
  on public.device_telemetry (device_id, created_at desc);

create index if not exists idx_actuation_logs_device_created_at
  on public.actuation_logs (device_id, created_at desc);

create index if not exists idx_security_events_device_created_at
  on public.security_events (device_id, created_at desc);

create or replace view public.dashboard_recent_records_v
with (security_invoker = true)
as
select
  id,
  device_id,
  timestamp,
  created_at,
  disease_id,
  disease_class_id,
  disease,
  disease_cn,
  confidence,
  risk_level,
  temperature_c,
  humidity_percent,
  light_lux,
  soil_moisture_percent,
  liquid_level,
  pump_action,
  fan_action,
  pump_duration_s,
  fan_duration_s,
  current_ma,
  alarm,
  pesticide,
  suggestion,
  inference_source,
  model_name,
  image_name,
  system_status,
  sensor_status
from public.diagnosis_records
order by created_at desc
limit 200;

create or replace view public.dashboard_node_status_v
with (security_invoker = true)
as
with latest as (
  select distinct on (device_id)
    device_id,
    created_at,
    disease_cn,
    risk_level,
    pump_action,
    fan_action,
    system_status,
    sensor_status
  from public.diagnosis_records
  order by device_id, created_at desc
)
select
  r.device_id,
  r.display_name,
  r.region_name,
  r.crop_type,
  coalesce(l.created_at, r.last_seen_at) as last_seen_at,
  case
    when coalesce(l.created_at, r.last_seen_at) is null then 'UNKNOWN'
    when now() - coalesce(l.created_at, r.last_seen_at) <= interval '2 minutes' then 'ONLINE'
    when now() - coalesce(l.created_at, r.last_seen_at) <= interval '10 minutes' then 'RECENT'
    else 'OFFLINE'
  end as online_status,
  coalesce(l.risk_level, 'UNKNOWN') as latest_risk_level,
  coalesce(l.disease_cn, '--') as latest_disease_cn,
  coalesce(l.pump_action, '--') as latest_pump_action,
  coalesce(l.fan_action, '--') as latest_fan_action,
  coalesce(l.system_status, 'UNKNOWN') as system_status,
  coalesce(l.sensor_status, 'UNKNOWN') as sensor_status
from public.device_registry r
left join latest l on l.device_id = r.device_id
where r.is_active = true
order by r.device_id;

create or replace view public.dashboard_risk_summary_v
with (security_invoker = true)
as
select
  risk_level,
  count(*) as record_count,
  max(created_at) as latest_at
from public.diagnosis_records
group by risk_level;

create or replace view public.dashboard_heatmap_24h_v
with (security_invoker = true)
as
select
  device_id,
  date_trunc('hour', created_at) as hour_bucket,
  count(*) as record_count,
  max(case risk_level
    when 'CRITICAL' then 5
    when 'HIGH' then 4
    when 'MEDIUM_HIGH' then 3
    when 'MEDIUM' then 2
    when 'LOW' then 1
    else 0
  end) as max_risk_score,
  max(risk_level) as max_risk_level
from public.diagnosis_records
where created_at >= now() - interval '24 hours'
group by device_id, date_trunc('hour', created_at);

create or replace view public.dashboard_alerts_v
with (security_invoker = true)
as
select
  id as record_id,
  created_at,
  device_id,
  risk_level,
  disease_cn,
  alarm,
  case
    when alarm <> 'NONE' then alarm
    when liquid_level = 'LOW' then 'LOW_LIQUID'
    when confidence < 0.6 then 'LOW_CONFIDENCE'
    when risk_level in ('HIGH', 'CRITICAL', 'MEDIUM_HIGH') then 'HIGH_RISK'
    else 'INFO'
  end as alert_type,
  suggestion as suggested_action
from public.diagnosis_records
where risk_level in ('HIGH', 'CRITICAL', 'MEDIUM_HIGH')
   or liquid_level = 'LOW'
   or alarm <> 'NONE'
   or confidence < 0.6
order by created_at desc;

alter table public.diagnosis_records enable row level security;
alter table public.action_records enable row level security;
alter table public.device_registry enable row level security;
alter table public.device_telemetry enable row level security;
alter table public.actuation_logs enable row level security;
alter table public.security_events enable row level security;
alter table public.model_versions enable row level security;

grant select on public.dashboard_recent_records_v to anon, authenticated;
grant select on public.dashboard_node_status_v to anon, authenticated;
grant select on public.dashboard_risk_summary_v to anon, authenticated;
grant select on public.dashboard_heatmap_24h_v to anon, authenticated;
grant select on public.dashboard_alerts_v to anon, authenticated;

grant select, insert on public.diagnosis_records to service_role;
grant select, insert, update on public.device_registry to service_role;
grant select, insert on public.device_telemetry to service_role;
grant select, insert on public.actuation_logs to service_role;
grant select, insert on public.security_events to service_role;
grant select, insert, update on public.model_versions to service_role;

grant usage, select on all sequences in schema public to service_role;

commit;
