-- Add hardware status fields and REQUEST relay state support.
-- Safe to run after 001_formal_schema_extension.sql. It does not delete data.

begin;

alter table public.diagnosis_records
  add column if not exists system_status text not null default 'UNKNOWN',
  add column if not exists sensor_status text not null default 'UNKNOWN';

alter table public.diagnosis_records
  drop constraint if exists diagnosis_records_pump_action_check,
  add constraint diagnosis_records_pump_action_check
    check (pump_action in ('ON', 'OFF', 'NONE', 'REQUEST'));

alter table public.diagnosis_records
  drop constraint if exists diagnosis_records_fan_action_check,
  add constraint diagnosis_records_fan_action_check
    check (fan_action in ('ON', 'OFF', 'NONE', 'REQUEST'));

create table if not exists public.device_registry (
  id bigint generated by default as identity primary key,
  device_id text not null unique check (device_id in ('Node01', 'Node02', 'Node03')),
  display_name text not null,
  region_name text not null,
  crop_type text not null,
  is_active boolean not null default true,
  token_version text not null default 'v1',
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.device_registry (device_id, display_name, region_name, crop_type)
values
  ('Node01', 'Node01 番茄区', '番茄区', '番茄'),
  ('Node02', 'Node02 甜椒区', '甜椒区', '甜椒'),
  ('Node03', 'Node03 马铃薯区', '马铃薯区', '马铃薯')
on conflict (device_id) do update
set display_name = excluded.display_name,
    region_name = excluded.region_name,
    crop_type = excluded.crop_type,
    updated_at = now();

alter table public.device_registry enable row level security;

alter table if exists public.actuation_logs
  drop constraint if exists actuation_logs_pump_action_check,
  add constraint actuation_logs_pump_action_check
    check (pump_action in ('ON', 'OFF', 'NONE', 'REQUEST'));

alter table if exists public.actuation_logs
  drop constraint if exists actuation_logs_fan_action_check,
  add constraint actuation_logs_fan_action_check
    check (fan_action in ('ON', 'OFF', 'NONE', 'REQUEST'));

create index if not exists idx_diagnosis_records_system_created_at
  on public.diagnosis_records (system_status, created_at desc);

create index if not exists idx_diagnosis_records_sensor_created_at
  on public.diagnosis_records (sensor_status, created_at desc);

create or replace view public.dashboard_recent_records_v
with (security_invoker = true)
as
select
  id,
  device_id,
  timestamp,
  created_at,
  disease_id,
  disease_class_id,
  disease,
  disease_cn,
  confidence,
  risk_level,
  temperature_c,
  humidity_percent,
  light_lux,
  soil_moisture_percent,
  liquid_level,
  pump_action,
  fan_action,
  pump_duration_s,
  fan_duration_s,
  current_ma,
  alarm,
  pesticide,
  suggestion,
  inference_source,
  model_name,
  image_name,
  system_status,
  sensor_status
from public.diagnosis_records
order by created_at desc
limit 200;

create or replace view public.dashboard_node_status_v
with (security_invoker = true)
as
with latest as (
  select distinct on (device_id)
    device_id,
    created_at,
    disease_cn,
    risk_level,
    pump_action,
    fan_action,
    system_status,
    sensor_status
  from public.diagnosis_records
  order by device_id, created_at desc
)
select
  r.device_id,
  r.display_name,
  r.region_name,
  r.crop_type,
  coalesce(l.created_at, r.last_seen_at) as last_seen_at,
  coalesce(l.system_status,
    case
      when coalesce(l.created_at, r.last_seen_at) is null then 'UNKNOWN'
      when now() - coalesce(l.created_at, r.last_seen_at) <= interval '2 minutes' then 'ONLINE'
      when now() - coalesce(l.created_at, r.last_seen_at) <= interval '10 minutes' then 'RECENT'
      else 'OFFLINE'
    end
  ) as online_status,
  coalesce(l.sensor_status, 'UNKNOWN') as sensor_status,
  coalesce(l.risk_level, 'UNKNOWN') as latest_risk_level,
  coalesce(l.disease_cn, '--') as latest_disease_cn,
  coalesce(l.pump_action, '--') as latest_pump_action,
  coalesce(l.fan_action, '--') as latest_fan_action
from public.device_registry r
left join latest l on l.device_id = r.device_id
where r.is_active = true
order by r.device_id;

grant select on public.dashboard_recent_records_v to anon, authenticated;
grant select on public.dashboard_node_status_v to anon, authenticated;
grant select (device_id, display_name, region_name, crop_type, is_active, last_seen_at, created_at, updated_at)
  on public.device_registry to anon, authenticated;
grant select, insert, update on public.device_registry to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
