-- STM32N647 agriculture dashboard schema for Supabase PostgreSQL.
-- Run this in Supabase SQL Editor if the tables do not exist yet.

create table if not exists public.diagnosis_records (
  id bigint generated by default as identity primary key,
  schema_version text not null default '1.0',
  timestamp timestamptz not null default now(),
  device_id text not null,
  image_url text,
  disease_id text not null,
  disease_class_id integer,
  disease text,
  disease_cn text not null,
  confidence numeric not null check (confidence >= 0 and confidence <= 1),
  risk_level text not null check (risk_level in ('LOW', 'MEDIUM', 'MEDIUM_HIGH', 'HIGH', 'UNKNOWN')),
  pesticide text,
  suggestion text,
  pump_action text not null default 'OFF' check (pump_action in ('ON', 'OFF', 'NONE', 'REQUEST')),
  fan_action text not null default 'OFF' check (fan_action in ('ON', 'OFF', 'NONE', 'REQUEST')),
  pump_duration_s integer not null default 0 check (pump_duration_s >= 0),
  fan_duration_s integer not null default 0 check (fan_duration_s >= 0),
  action_duration_s integer not null default 0 check (action_duration_s >= 0),
  temperature_c double precision,
  humidity_percent double precision,
  light_lux double precision,
  soil_moisture_percent double precision,
  temperature numeric,
  humidity numeric,
  light integer,
  soil_moisture integer,
  liquid_level text,
  current_ma numeric,
  system_status text not null default 'UNKNOWN',
  sensor_status text not null default 'UNKNOWN',
  alarm text not null default 'NONE',
  inference_source text not null default 'simulated',
  model_name text,
  image_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.action_records (
  id bigint generated by default as identity primary key,
  device_id text not null,
  timestamp timestamp not null default now(),
  action text not null check (action in ('NONE', 'SPRAY', 'VENTILATE', 'SPRAY_AND_VENTILATE')),
  result text not null default 'EXECUTED',
  created_at timestamptz default now()
);

create index if not exists idx_diagnosis_records_timestamp
  on public.diagnosis_records (timestamp desc);

create index if not exists idx_diagnosis_records_device_time
  on public.diagnosis_records (device_id, timestamp desc);

create index if not exists idx_diagnosis_records_risk
  on public.diagnosis_records (risk_level);

alter table public.diagnosis_records enable row level security;
alter table public.action_records enable row level security;

grant select, insert on public.diagnosis_records to anon, authenticated;
grant select, insert on public.action_records to anon, authenticated;
grant usage, select on sequence public.diagnosis_records_id_seq to anon, authenticated;
grant usage, select on sequence public.action_records_id_seq to anon, authenticated;

drop policy if exists demo_read_diagnosis_records on public.diagnosis_records;
create policy demo_read_diagnosis_records
on public.diagnosis_records
for select
to anon, authenticated
using (true);

drop policy if exists demo_insert_diagnosis_records on public.diagnosis_records;
create policy demo_insert_diagnosis_records
on public.diagnosis_records
for insert
to anon, authenticated
with check (true);

drop policy if exists demo_read_action_records on public.action_records;
create policy demo_read_action_records
on public.action_records
for select
to anon, authenticated
using (true);

drop policy if exists demo_insert_action_records on public.action_records;
create policy demo_insert_action_records
on public.action_records
for insert
to anon, authenticated
with check (true);
