/**
  ******************************************************************************
  * @file    network.h
  * @date    2026-07-02T11:22:37+0800
  * @brief   ST.AI Tool Automatic Code Generator for Embedded NN computing
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
  */
#ifndef STAI_NETWORK_DETAILS_H
#define STAI_NETWORK_DETAILS_H

#include "stai.h"
#include "layers.h"

const stai_network_details g_network_details = {
  .tensors = (const stai_tensor[157]) {
   { .size_bytes = 602112, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 3, 224, 224}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "images_output" },
   { .size_bytes = 602112, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 224, 224, 3}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "images_Transpose_output" },
   { .size_bytes = 802816, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 112, 112, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_0_conv_Conv_output_0_output" },
   { .size_bytes = 802816, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 112, 112, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_0_act_Sigmoid_output_0_output" },
   { .size_bytes = 802816, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 112, 112, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_0_act_Mul_output_0_output" },
   { .size_bytes = 401408, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_1_conv_Conv_output_0_output" },
   { .size_bytes = 401408, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_1_act_Sigmoid_output_0_output" },
   { .size_bytes = 401408, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_1_act_Mul_output_0_output" },
   { .size_bytes = 401408, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 401408, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 401408, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_cv1_act_Mul_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_Split_output_0_output0" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_Split_output_0_output1" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 8}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_m_0_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 8}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_m_0_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 8}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_m_0_cv1_act_Mul_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_m_0_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_m_0_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_m_0_cv2_act_Mul_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_m_0_Add_output_0_output" },
   { .size_bytes = 602112, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 48}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_Concat_output_0_output" },
   { .size_bytes = 802816, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 802816, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 802816, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 56, 56, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_2_cv2_act_Mul_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_3_conv_Conv_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_3_act_Sigmoid_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_3_act_Mul_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 200704, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_cv1_act_Mul_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_Split_output_0_output0" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_Split_output_0_output1" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_m_0_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_m_0_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 16}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_m_0_cv1_act_Mul_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_m_0_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_m_0_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_m_0_cv2_act_Mul_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_m_0_Add_output_0_output" },
   { .size_bytes = 301056, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 96}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_Concat_output_0_output" },
   { .size_bytes = 401408, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 401408, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 401408, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 28, 28, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_4_cv2_act_Mul_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_5_conv_Conv_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_5_act_Sigmoid_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_5_act_Mul_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_cv1_act_Mul_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_Split_output_0_output0" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_Split_output_0_output1" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_cv2_act_Mul_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_cv1_act_Mul_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_0_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_0_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_0_cv1_act_Mul_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_0_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_0_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_0_cv2_act_Mul_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_0_Add_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_1_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_1_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_1_cv1_act_Mul_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_1_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_1_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_1_cv2_act_Mul_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_m_m_1_Add_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_Concat_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_cv3_conv_Conv_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_cv3_act_Sigmoid_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_m_0_cv3_act_Mul_output_0_output" },
   { .size_bytes = 150528, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 192}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_Concat_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 100352, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 14, 14, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_6_cv2_act_Mul_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_7_conv_Conv_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_7_act_Sigmoid_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_7_act_Mul_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_cv1_act_Mul_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_Split_output_0_output0" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_Split_output_0_output1" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_cv2_act_Mul_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_cv1_act_Mul_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_0_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_0_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_0_cv1_act_Mul_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_0_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_0_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_0_cv2_act_Mul_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_0_Add_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_1_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_1_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_1_cv1_act_Mul_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_1_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_1_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_1_cv2_act_Mul_output_0_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 64}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_m_m_1_Add_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_Concat_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_cv3_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_cv3_act_Sigmoid_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_m_0_cv3_act_Mul_output_0_output" },
   { .size_bytes = 75264, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 384}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_Concat_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_8_cv2_act_Mul_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_cv1_conv_Conv_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_cv1_act_Sigmoid_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_cv1_act_Mul_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_Split_output_0_output0" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_Split_output_0_output1" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_qkv_conv_Conv_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 256, 7, 7}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Reshape_output_0_to_chlast_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 128, 49, 2}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Reshape_output_0_to_chfirst_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 32, 49, 2}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Split_output_0_output0" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 32, 49, 2}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Split_output_0_output1" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 64, 49, 2}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Split_output_0_output2" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 2, 49, 32}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "transpose_a_model_9_m_m_0_attn_MatMul_output_0_out_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 2, 64, 49}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "transpose_a_model_9_m_m_0_attn_MatMul_1_output_0_out_output" },
   { .size_bytes = 12544, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 2, 32, 49}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "transpose_b_model_9_m_m_0_attn_MatMul_output_0_out_output" },
   { .size_bytes = 19208, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 2, 49, 49}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_MatMul_output_0_output" },
   { .size_bytes = 19208, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 49, 49, 2}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "transpose_out_model_9_m_m_0_attn_MatMul_output_0_out_output" },
   { .size_bytes = 19208, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 49, 49, 2}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Mul_output_0_output" },
   { .size_bytes = 19208, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 49, 49, 2}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Softmax_output_0_output" },
   { .size_bytes = 19208, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 2, 49, 49}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "transpose_b_model_9_m_m_0_attn_MatMul_1_output_0_out_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 2, 64, 49}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_MatMul_1_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Reshape_1_output_0_to_chfirst_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 2, 64, 49}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Reshape_2_output_0_to_chlast_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Reshape_2_output_0_to_chfirst_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_pe_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_Add_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_attn_proj_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_Add_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_ffn_ffn_0_conv_Conv_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_ffn_ffn_0_act_Sigmoid_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_ffn_ffn_0_act_Mul_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_ffn_ffn_1_conv_Conv_output_0_output" },
   { .size_bytes = 25088, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 128}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_m_m_0_Add_1_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_Concat_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_cv2_conv_Conv_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_cv2_act_Sigmoid_output_0_output" },
   { .size_bytes = 50176, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 256}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_9_cv2_act_Mul_output_0_output" },
   { .size_bytes = 250880, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 1280}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_10_conv_conv_Conv_output_0_output" },
   { .size_bytes = 250880, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 1280}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_10_conv_act_Sigmoid_output_0_output" },
   { .size_bytes = 250880, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 7, 7, 1280}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_10_conv_act_Mul_output_0_output" },
   { .size_bytes = 5120, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {4, (const int32_t[4]){1, 1, 1, 1280}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_10_pool_GlobalAveragePool_output_0_output" },
   { .size_bytes = 32, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {2, (const int32_t[2]){1, 8}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "_model_10_linear_Gemm_output_0_output" },
   { .size_bytes = 32, .flags = (STAI_FLAG_HAS_BATCH|STAI_FLAG_CHANNEL_LAST), .format = STAI_FORMAT_FLOAT32, .shape = {2, (const int32_t[2]){1, 8}}, .scale = {0, NULL}, .zeropoint = {0, NULL}, .name = "output0_output" }
  },
  .nodes = (const stai_node_details[149]){
    {.id = 2, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){0}}, .output_tensors = {1, (const int32_t[1]){1}} }, /* images_Transpose */
    {.id = 1, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){1}}, .output_tensors = {1, (const int32_t[1]){2}} }, /* _model_0_conv_Conv_output_0 */
    {.id = 2, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){2}}, .output_tensors = {1, (const int32_t[1]){3}} }, /* _model_0_act_Sigmoid_output_0 */
    {.id = 3, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){2, 3}}, .output_tensors = {1, (const int32_t[1]){4}} }, /* _model_0_act_Mul_output_0 */
    {.id = 4, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){4}}, .output_tensors = {1, (const int32_t[1]){5}} }, /* _model_1_conv_Conv_output_0 */
    {.id = 5, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){5}}, .output_tensors = {1, (const int32_t[1]){6}} }, /* _model_1_act_Sigmoid_output_0 */
    {.id = 6, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){5, 6}}, .output_tensors = {1, (const int32_t[1]){7}} }, /* _model_1_act_Mul_output_0 */
    {.id = 7, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){7}}, .output_tensors = {1, (const int32_t[1]){8}} }, /* _model_2_cv1_conv_Conv_output_0 */
    {.id = 8, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){8}}, .output_tensors = {1, (const int32_t[1]){9}} }, /* _model_2_cv1_act_Sigmoid_output_0 */
    {.id = 9, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){8, 9}}, .output_tensors = {1, (const int32_t[1]){10}} }, /* _model_2_cv1_act_Mul_output_0 */
    {.id = 11, .type = AI_LAYER_SPLIT_TYPE, .input_tensors = {1, (const int32_t[1]){10}}, .output_tensors = {2, (const int32_t[2]){11, 12}} }, /* _model_2_Split_output_0 */
    {.id = 12, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){12}}, .output_tensors = {1, (const int32_t[1]){13}} }, /* _model_2_m_0_cv1_conv_Conv_output_0 */
    {.id = 13, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){13}}, .output_tensors = {1, (const int32_t[1]){14}} }, /* _model_2_m_0_cv1_act_Sigmoid_output_0 */
    {.id = 14, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){13, 14}}, .output_tensors = {1, (const int32_t[1]){15}} }, /* _model_2_m_0_cv1_act_Mul_output_0 */
    {.id = 15, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){15}}, .output_tensors = {1, (const int32_t[1]){16}} }, /* _model_2_m_0_cv2_conv_Conv_output_0 */
    {.id = 16, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){16}}, .output_tensors = {1, (const int32_t[1]){17}} }, /* _model_2_m_0_cv2_act_Sigmoid_output_0 */
    {.id = 17, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){16, 17}}, .output_tensors = {1, (const int32_t[1]){18}} }, /* _model_2_m_0_cv2_act_Mul_output_0 */
    {.id = 18, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){12, 18}}, .output_tensors = {1, (const int32_t[1]){19}} }, /* _model_2_m_0_Add_output_0 */
    {.id = 19, .type = AI_LAYER_CONCAT_TYPE, .input_tensors = {3, (const int32_t[3]){11, 12, 19}}, .output_tensors = {1, (const int32_t[1]){20}} }, /* _model_2_Concat_output_0 */
    {.id = 20, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){20}}, .output_tensors = {1, (const int32_t[1]){21}} }, /* _model_2_cv2_conv_Conv_output_0 */
    {.id = 21, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){21}}, .output_tensors = {1, (const int32_t[1]){22}} }, /* _model_2_cv2_act_Sigmoid_output_0 */
    {.id = 22, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){21, 22}}, .output_tensors = {1, (const int32_t[1]){23}} }, /* _model_2_cv2_act_Mul_output_0 */
    {.id = 23, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){23}}, .output_tensors = {1, (const int32_t[1]){24}} }, /* _model_3_conv_Conv_output_0 */
    {.id = 24, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){24}}, .output_tensors = {1, (const int32_t[1]){25}} }, /* _model_3_act_Sigmoid_output_0 */
    {.id = 25, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){24, 25}}, .output_tensors = {1, (const int32_t[1]){26}} }, /* _model_3_act_Mul_output_0 */
    {.id = 26, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){26}}, .output_tensors = {1, (const int32_t[1]){27}} }, /* _model_4_cv1_conv_Conv_output_0 */
    {.id = 27, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){27}}, .output_tensors = {1, (const int32_t[1]){28}} }, /* _model_4_cv1_act_Sigmoid_output_0 */
    {.id = 28, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){27, 28}}, .output_tensors = {1, (const int32_t[1]){29}} }, /* _model_4_cv1_act_Mul_output_0 */
    {.id = 30, .type = AI_LAYER_SPLIT_TYPE, .input_tensors = {1, (const int32_t[1]){29}}, .output_tensors = {2, (const int32_t[2]){30, 31}} }, /* _model_4_Split_output_0 */
    {.id = 31, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){31}}, .output_tensors = {1, (const int32_t[1]){32}} }, /* _model_4_m_0_cv1_conv_Conv_output_0 */
    {.id = 32, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){32}}, .output_tensors = {1, (const int32_t[1]){33}} }, /* _model_4_m_0_cv1_act_Sigmoid_output_0 */
    {.id = 33, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){32, 33}}, .output_tensors = {1, (const int32_t[1]){34}} }, /* _model_4_m_0_cv1_act_Mul_output_0 */
    {.id = 34, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){34}}, .output_tensors = {1, (const int32_t[1]){35}} }, /* _model_4_m_0_cv2_conv_Conv_output_0 */
    {.id = 35, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){35}}, .output_tensors = {1, (const int32_t[1]){36}} }, /* _model_4_m_0_cv2_act_Sigmoid_output_0 */
    {.id = 36, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){35, 36}}, .output_tensors = {1, (const int32_t[1]){37}} }, /* _model_4_m_0_cv2_act_Mul_output_0 */
    {.id = 37, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){31, 37}}, .output_tensors = {1, (const int32_t[1]){38}} }, /* _model_4_m_0_Add_output_0 */
    {.id = 38, .type = AI_LAYER_CONCAT_TYPE, .input_tensors = {3, (const int32_t[3]){30, 31, 38}}, .output_tensors = {1, (const int32_t[1]){39}} }, /* _model_4_Concat_output_0 */
    {.id = 39, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){39}}, .output_tensors = {1, (const int32_t[1]){40}} }, /* _model_4_cv2_conv_Conv_output_0 */
    {.id = 40, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){40}}, .output_tensors = {1, (const int32_t[1]){41}} }, /* _model_4_cv2_act_Sigmoid_output_0 */
    {.id = 41, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){40, 41}}, .output_tensors = {1, (const int32_t[1]){42}} }, /* _model_4_cv2_act_Mul_output_0 */
    {.id = 42, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){42}}, .output_tensors = {1, (const int32_t[1]){43}} }, /* _model_5_conv_Conv_output_0 */
    {.id = 43, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){43}}, .output_tensors = {1, (const int32_t[1]){44}} }, /* _model_5_act_Sigmoid_output_0 */
    {.id = 44, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){43, 44}}, .output_tensors = {1, (const int32_t[1]){45}} }, /* _model_5_act_Mul_output_0 */
    {.id = 45, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){45}}, .output_tensors = {1, (const int32_t[1]){46}} }, /* _model_6_cv1_conv_Conv_output_0 */
    {.id = 46, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){46}}, .output_tensors = {1, (const int32_t[1]){47}} }, /* _model_6_cv1_act_Sigmoid_output_0 */
    {.id = 47, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){46, 47}}, .output_tensors = {1, (const int32_t[1]){48}} }, /* _model_6_cv1_act_Mul_output_0 */
    {.id = 49, .type = AI_LAYER_SPLIT_TYPE, .input_tensors = {1, (const int32_t[1]){48}}, .output_tensors = {2, (const int32_t[2]){49, 50}} }, /* _model_6_Split_output_0 */
    {.id = 67, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){50}}, .output_tensors = {1, (const int32_t[1]){51}} }, /* _model_6_m_0_cv2_conv_Conv_output_0 */
    {.id = 68, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){51}}, .output_tensors = {1, (const int32_t[1]){52}} }, /* _model_6_m_0_cv2_act_Sigmoid_output_0 */
    {.id = 69, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){51, 52}}, .output_tensors = {1, (const int32_t[1]){53}} }, /* _model_6_m_0_cv2_act_Mul_output_0 */
    {.id = 50, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){50}}, .output_tensors = {1, (const int32_t[1]){54}} }, /* _model_6_m_0_cv1_conv_Conv_output_0 */
    {.id = 51, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){54}}, .output_tensors = {1, (const int32_t[1]){55}} }, /* _model_6_m_0_cv1_act_Sigmoid_output_0 */
    {.id = 52, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){54, 55}}, .output_tensors = {1, (const int32_t[1]){56}} }, /* _model_6_m_0_cv1_act_Mul_output_0 */
    {.id = 53, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){56}}, .output_tensors = {1, (const int32_t[1]){57}} }, /* _model_6_m_0_m_m_0_cv1_conv_Conv_output_0 */
    {.id = 54, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){57}}, .output_tensors = {1, (const int32_t[1]){58}} }, /* _model_6_m_0_m_m_0_cv1_act_Sigmoid_output_0 */
    {.id = 55, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){57, 58}}, .output_tensors = {1, (const int32_t[1]){59}} }, /* _model_6_m_0_m_m_0_cv1_act_Mul_output_0 */
    {.id = 56, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){59}}, .output_tensors = {1, (const int32_t[1]){60}} }, /* _model_6_m_0_m_m_0_cv2_conv_Conv_output_0 */
    {.id = 57, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){60}}, .output_tensors = {1, (const int32_t[1]){61}} }, /* _model_6_m_0_m_m_0_cv2_act_Sigmoid_output_0 */
    {.id = 58, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){60, 61}}, .output_tensors = {1, (const int32_t[1]){62}} }, /* _model_6_m_0_m_m_0_cv2_act_Mul_output_0 */
    {.id = 59, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){56, 62}}, .output_tensors = {1, (const int32_t[1]){63}} }, /* _model_6_m_0_m_m_0_Add_output_0 */
    {.id = 60, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){63}}, .output_tensors = {1, (const int32_t[1]){64}} }, /* _model_6_m_0_m_m_1_cv1_conv_Conv_output_0 */
    {.id = 61, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){64}}, .output_tensors = {1, (const int32_t[1]){65}} }, /* _model_6_m_0_m_m_1_cv1_act_Sigmoid_output_0 */
    {.id = 62, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){64, 65}}, .output_tensors = {1, (const int32_t[1]){66}} }, /* _model_6_m_0_m_m_1_cv1_act_Mul_output_0 */
    {.id = 63, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){66}}, .output_tensors = {1, (const int32_t[1]){67}} }, /* _model_6_m_0_m_m_1_cv2_conv_Conv_output_0 */
    {.id = 64, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){67}}, .output_tensors = {1, (const int32_t[1]){68}} }, /* _model_6_m_0_m_m_1_cv2_act_Sigmoid_output_0 */
    {.id = 65, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){67, 68}}, .output_tensors = {1, (const int32_t[1]){69}} }, /* _model_6_m_0_m_m_1_cv2_act_Mul_output_0 */
    {.id = 66, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){63, 69}}, .output_tensors = {1, (const int32_t[1]){70}} }, /* _model_6_m_0_m_m_1_Add_output_0 */
    {.id = 70, .type = AI_LAYER_CONCAT_TYPE, .input_tensors = {2, (const int32_t[2]){70, 53}}, .output_tensors = {1, (const int32_t[1]){71}} }, /* _model_6_m_0_Concat_output_0 */
    {.id = 71, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){71}}, .output_tensors = {1, (const int32_t[1]){72}} }, /* _model_6_m_0_cv3_conv_Conv_output_0 */
    {.id = 72, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){72}}, .output_tensors = {1, (const int32_t[1]){73}} }, /* _model_6_m_0_cv3_act_Sigmoid_output_0 */
    {.id = 73, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){72, 73}}, .output_tensors = {1, (const int32_t[1]){74}} }, /* _model_6_m_0_cv3_act_Mul_output_0 */
    {.id = 74, .type = AI_LAYER_CONCAT_TYPE, .input_tensors = {3, (const int32_t[3]){49, 50, 74}}, .output_tensors = {1, (const int32_t[1]){75}} }, /* _model_6_Concat_output_0 */
    {.id = 75, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){75}}, .output_tensors = {1, (const int32_t[1]){76}} }, /* _model_6_cv2_conv_Conv_output_0 */
    {.id = 76, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){76}}, .output_tensors = {1, (const int32_t[1]){77}} }, /* _model_6_cv2_act_Sigmoid_output_0 */
    {.id = 77, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){76, 77}}, .output_tensors = {1, (const int32_t[1]){78}} }, /* _model_6_cv2_act_Mul_output_0 */
    {.id = 78, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){78}}, .output_tensors = {1, (const int32_t[1]){79}} }, /* _model_7_conv_Conv_output_0 */
    {.id = 79, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){79}}, .output_tensors = {1, (const int32_t[1]){80}} }, /* _model_7_act_Sigmoid_output_0 */
    {.id = 80, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){79, 80}}, .output_tensors = {1, (const int32_t[1]){81}} }, /* _model_7_act_Mul_output_0 */
    {.id = 81, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){81}}, .output_tensors = {1, (const int32_t[1]){82}} }, /* _model_8_cv1_conv_Conv_output_0 */
    {.id = 82, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){82}}, .output_tensors = {1, (const int32_t[1]){83}} }, /* _model_8_cv1_act_Sigmoid_output_0 */
    {.id = 83, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){82, 83}}, .output_tensors = {1, (const int32_t[1]){84}} }, /* _model_8_cv1_act_Mul_output_0 */
    {.id = 85, .type = AI_LAYER_SPLIT_TYPE, .input_tensors = {1, (const int32_t[1]){84}}, .output_tensors = {2, (const int32_t[2]){85, 86}} }, /* _model_8_Split_output_0 */
    {.id = 103, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){86}}, .output_tensors = {1, (const int32_t[1]){87}} }, /* _model_8_m_0_cv2_conv_Conv_output_0 */
    {.id = 104, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){87}}, .output_tensors = {1, (const int32_t[1]){88}} }, /* _model_8_m_0_cv2_act_Sigmoid_output_0 */
    {.id = 105, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){87, 88}}, .output_tensors = {1, (const int32_t[1]){89}} }, /* _model_8_m_0_cv2_act_Mul_output_0 */
    {.id = 86, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){86}}, .output_tensors = {1, (const int32_t[1]){90}} }, /* _model_8_m_0_cv1_conv_Conv_output_0 */
    {.id = 87, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){90}}, .output_tensors = {1, (const int32_t[1]){91}} }, /* _model_8_m_0_cv1_act_Sigmoid_output_0 */
    {.id = 88, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){90, 91}}, .output_tensors = {1, (const int32_t[1]){92}} }, /* _model_8_m_0_cv1_act_Mul_output_0 */
    {.id = 89, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){92}}, .output_tensors = {1, (const int32_t[1]){93}} }, /* _model_8_m_0_m_m_0_cv1_conv_Conv_output_0 */
    {.id = 90, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){93}}, .output_tensors = {1, (const int32_t[1]){94}} }, /* _model_8_m_0_m_m_0_cv1_act_Sigmoid_output_0 */
    {.id = 91, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){93, 94}}, .output_tensors = {1, (const int32_t[1]){95}} }, /* _model_8_m_0_m_m_0_cv1_act_Mul_output_0 */
    {.id = 92, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){95}}, .output_tensors = {1, (const int32_t[1]){96}} }, /* _model_8_m_0_m_m_0_cv2_conv_Conv_output_0 */
    {.id = 93, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){96}}, .output_tensors = {1, (const int32_t[1]){97}} }, /* _model_8_m_0_m_m_0_cv2_act_Sigmoid_output_0 */
    {.id = 94, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){96, 97}}, .output_tensors = {1, (const int32_t[1]){98}} }, /* _model_8_m_0_m_m_0_cv2_act_Mul_output_0 */
    {.id = 95, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){92, 98}}, .output_tensors = {1, (const int32_t[1]){99}} }, /* _model_8_m_0_m_m_0_Add_output_0 */
    {.id = 96, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){99}}, .output_tensors = {1, (const int32_t[1]){100}} }, /* _model_8_m_0_m_m_1_cv1_conv_Conv_output_0 */
    {.id = 97, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){100}}, .output_tensors = {1, (const int32_t[1]){101}} }, /* _model_8_m_0_m_m_1_cv1_act_Sigmoid_output_0 */
    {.id = 98, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){100, 101}}, .output_tensors = {1, (const int32_t[1]){102}} }, /* _model_8_m_0_m_m_1_cv1_act_Mul_output_0 */
    {.id = 99, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){102}}, .output_tensors = {1, (const int32_t[1]){103}} }, /* _model_8_m_0_m_m_1_cv2_conv_Conv_output_0 */
    {.id = 100, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){103}}, .output_tensors = {1, (const int32_t[1]){104}} }, /* _model_8_m_0_m_m_1_cv2_act_Sigmoid_output_0 */
    {.id = 101, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){103, 104}}, .output_tensors = {1, (const int32_t[1]){105}} }, /* _model_8_m_0_m_m_1_cv2_act_Mul_output_0 */
    {.id = 102, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){99, 105}}, .output_tensors = {1, (const int32_t[1]){106}} }, /* _model_8_m_0_m_m_1_Add_output_0 */
    {.id = 106, .type = AI_LAYER_CONCAT_TYPE, .input_tensors = {2, (const int32_t[2]){106, 89}}, .output_tensors = {1, (const int32_t[1]){107}} }, /* _model_8_m_0_Concat_output_0 */
    {.id = 107, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){107}}, .output_tensors = {1, (const int32_t[1]){108}} }, /* _model_8_m_0_cv3_conv_Conv_output_0 */
    {.id = 108, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){108}}, .output_tensors = {1, (const int32_t[1]){109}} }, /* _model_8_m_0_cv3_act_Sigmoid_output_0 */
    {.id = 109, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){108, 109}}, .output_tensors = {1, (const int32_t[1]){110}} }, /* _model_8_m_0_cv3_act_Mul_output_0 */
    {.id = 110, .type = AI_LAYER_CONCAT_TYPE, .input_tensors = {3, (const int32_t[3]){85, 86, 110}}, .output_tensors = {1, (const int32_t[1]){111}} }, /* _model_8_Concat_output_0 */
    {.id = 111, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){111}}, .output_tensors = {1, (const int32_t[1]){112}} }, /* _model_8_cv2_conv_Conv_output_0 */
    {.id = 112, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){112}}, .output_tensors = {1, (const int32_t[1]){113}} }, /* _model_8_cv2_act_Sigmoid_output_0 */
    {.id = 113, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){112, 113}}, .output_tensors = {1, (const int32_t[1]){114}} }, /* _model_8_cv2_act_Mul_output_0 */
    {.id = 114, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){114}}, .output_tensors = {1, (const int32_t[1]){115}} }, /* _model_9_cv1_conv_Conv_output_0 */
    {.id = 115, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){115}}, .output_tensors = {1, (const int32_t[1]){116}} }, /* _model_9_cv1_act_Sigmoid_output_0 */
    {.id = 116, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){115, 116}}, .output_tensors = {1, (const int32_t[1]){117}} }, /* _model_9_cv1_act_Mul_output_0 */
    {.id = 117, .type = AI_LAYER_SPLIT_TYPE, .input_tensors = {1, (const int32_t[1]){117}}, .output_tensors = {2, (const int32_t[2]){118, 119}} }, /* _model_9_Split_output_0 */
    {.id = 118, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){119}}, .output_tensors = {1, (const int32_t[1]){120}} }, /* _model_9_m_m_0_attn_qkv_conv_Conv_output_0 */
    {.id = 120, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){120}}, .output_tensors = {1, (const int32_t[1]){121}} }, /* _model_9_m_m_0_attn_Reshape_output_0_to_chlast */
    {.id = 120, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){121}}, .output_tensors = {1, (const int32_t[1]){122}} }, /* _model_9_m_m_0_attn_Reshape_output_0_to_chfirst */
    {.id = 122, .type = AI_LAYER_SPLIT_TYPE, .input_tensors = {1, (const int32_t[1]){122}}, .output_tensors = {3, (const int32_t[3]){123, 124, 125}} }, /* _model_9_m_m_0_attn_Split_output_0 */
    {.id = 124, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){123}}, .output_tensors = {1, (const int32_t[1]){126}} }, /* transpose_a_model_9_m_m_0_attn_MatMul_output_0_out */
    {.id = 129, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){125}}, .output_tensors = {1, (const int32_t[1]){127}} }, /* transpose_a_model_9_m_m_0_attn_MatMul_1_output_0_out */
    {.id = 124, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){124}}, .output_tensors = {1, (const int32_t[1]){128}} }, /* transpose_b_model_9_m_m_0_attn_MatMul_output_0_out */
    {.id = 124, .type = AI_LAYER_MATMUL_TYPE, .input_tensors = {2, (const int32_t[2]){126, 128}}, .output_tensors = {1, (const int32_t[1]){129}} }, /* _model_9_m_m_0_attn_MatMul_output_0 */
    {.id = 124, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){129}}, .output_tensors = {1, (const int32_t[1]){130}} }, /* transpose_out_model_9_m_m_0_attn_MatMul_output_0_out */
    {.id = 126, .type = AI_LAYER_BN_TYPE, .input_tensors = {1, (const int32_t[1]){130}}, .output_tensors = {1, (const int32_t[1]){131}} }, /* _model_9_m_m_0_attn_Mul_output_0 */
    {.id = 127, .type = AI_LAYER_SM_TYPE, .input_tensors = {1, (const int32_t[1]){131}}, .output_tensors = {1, (const int32_t[1]){132}} }, /* _model_9_m_m_0_attn_Softmax_output_0 */
    {.id = 129, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){132}}, .output_tensors = {1, (const int32_t[1]){133}} }, /* transpose_b_model_9_m_m_0_attn_MatMul_1_output_0_out */
    {.id = 129, .type = AI_LAYER_MATMUL_TYPE, .input_tensors = {2, (const int32_t[2]){127, 133}}, .output_tensors = {1, (const int32_t[1]){134}} }, /* _model_9_m_m_0_attn_MatMul_1_output_0 */
    {.id = 132, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){134}}, .output_tensors = {1, (const int32_t[1]){135}} }, /* _model_9_m_m_0_attn_Reshape_1_output_0_to_chfirst */
    {.id = 133, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){125}}, .output_tensors = {1, (const int32_t[1]){136}} }, /* _model_9_m_m_0_attn_Reshape_2_output_0_to_chlast */
    {.id = 133, .type = AI_LAYER_TRANSPOSE_TYPE, .input_tensors = {1, (const int32_t[1]){136}}, .output_tensors = {1, (const int32_t[1]){137}} }, /* _model_9_m_m_0_attn_Reshape_2_output_0_to_chfirst */
    {.id = 134, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){137}}, .output_tensors = {1, (const int32_t[1]){138}} }, /* _model_9_m_m_0_attn_pe_conv_Conv_output_0 */
    {.id = 135, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){135, 138}}, .output_tensors = {1, (const int32_t[1]){139}} }, /* _model_9_m_m_0_attn_Add_output_0 */
    {.id = 136, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){139}}, .output_tensors = {1, (const int32_t[1]){140}} }, /* _model_9_m_m_0_attn_proj_conv_Conv_output_0 */
    {.id = 137, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){119, 140}}, .output_tensors = {1, (const int32_t[1]){141}} }, /* _model_9_m_m_0_Add_output_0 */
    {.id = 138, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){141}}, .output_tensors = {1, (const int32_t[1]){142}} }, /* _model_9_m_m_0_ffn_ffn_0_conv_Conv_output_0 */
    {.id = 139, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){142}}, .output_tensors = {1, (const int32_t[1]){143}} }, /* _model_9_m_m_0_ffn_ffn_0_act_Sigmoid_output_0 */
    {.id = 140, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){142, 143}}, .output_tensors = {1, (const int32_t[1]){144}} }, /* _model_9_m_m_0_ffn_ffn_0_act_Mul_output_0 */
    {.id = 141, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){144}}, .output_tensors = {1, (const int32_t[1]){145}} }, /* _model_9_m_m_0_ffn_ffn_1_conv_Conv_output_0 */
    {.id = 142, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){141, 145}}, .output_tensors = {1, (const int32_t[1]){146}} }, /* _model_9_m_m_0_Add_1_output_0 */
    {.id = 143, .type = AI_LAYER_CONCAT_TYPE, .input_tensors = {2, (const int32_t[2]){118, 146}}, .output_tensors = {1, (const int32_t[1]){147}} }, /* _model_9_Concat_output_0 */
    {.id = 144, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){147}}, .output_tensors = {1, (const int32_t[1]){148}} }, /* _model_9_cv2_conv_Conv_output_0 */
    {.id = 145, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){148}}, .output_tensors = {1, (const int32_t[1]){149}} }, /* _model_9_cv2_act_Sigmoid_output_0 */
    {.id = 146, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){148, 149}}, .output_tensors = {1, (const int32_t[1]){150}} }, /* _model_9_cv2_act_Mul_output_0 */
    {.id = 147, .type = AI_LAYER_CONV2D_TYPE, .input_tensors = {1, (const int32_t[1]){150}}, .output_tensors = {1, (const int32_t[1]){151}} }, /* _model_10_conv_conv_Conv_output_0 */
    {.id = 148, .type = AI_LAYER_NL_TYPE, .input_tensors = {1, (const int32_t[1]){151}}, .output_tensors = {1, (const int32_t[1]){152}} }, /* _model_10_conv_act_Sigmoid_output_0 */
    {.id = 149, .type = AI_LAYER_ELTWISE_TYPE, .input_tensors = {2, (const int32_t[2]){151, 152}}, .output_tensors = {1, (const int32_t[1]){153}} }, /* _model_10_conv_act_Mul_output_0 */
    {.id = 150, .type = AI_LAYER_POOL_TYPE, .input_tensors = {1, (const int32_t[1]){153}}, .output_tensors = {1, (const int32_t[1]){154}} }, /* _model_10_pool_GlobalAveragePool_output_0 */
    {.id = 152, .type = AI_LAYER_DENSE_TYPE, .input_tensors = {1, (const int32_t[1]){154}}, .output_tensors = {1, (const int32_t[1]){155}} }, /* _model_10_linear_Gemm_output_0 */
    {.id = 153, .type = AI_LAYER_SM_TYPE, .input_tensors = {1, (const int32_t[1]){155}}, .output_tensors = {1, (const int32_t[1]){156}} } /* output0 */
  },
  .n_nodes = 149
};
#endif

